version: '3.8'

services:
  ## mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "!QAZ2wsx"
    ports:
      - "1433:1433"
    volumes:
      - ./data/mssql:/var/opt/mssql/data
